### ISSUE TITLE
Errors, inability to finish stage_b or initiate stage_c

### ISSUE THREAD

**Issue by dduchen** [HaploConduct/HaploConduct#10]
Hello,
Thank you for all your work with this package, I'm not sure what's causing this error so any help would be greatly appreciated. I've tried with a range of memory options/input fastq files (all with a single fastq file), I'm using savage de-novo, and can't seem to get through stage_b.

Error:

`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Traceback (most recent call last):
  File "/home-1/dduchen3@jhu.edu/code/dduchen_tools/miniconda3/envs/haploconduct/opt/haploconduct-0.2.1/scripts/pipeline_per_stage.py", line 666, in <module>
    sys.exit(main())
  File "/home-1/dduchen3@jhu.edu/code/dduchen_tools/miniconda3/envs/haploconduct/opt/haploconduct-0.2.1/scripts/pipeline_per_stage.py", line 164, in main
    run_first_it_merge(args.fastq, args.overlaps, args.edge_threshold, args.min_overlap_perc, min_overlap_len, args.merge_contigs, first_it)
  File "/home-1/dduchen3@jhu.edu/code/dduchen_tools/miniconda3/envs/haploconduct/opt/haploconduct-0.2.1/scripts/pipeline_per_stage.py", line 246, in run_first_it_merge
    "--ignore_inclusions=%s" % remove_inclusions
  File "/home-1/dduchen3@jhu.edu/code/dduchen_tools/miniconda3/envs/haploconduct/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home-1/dduchen3@jhu.edu/code/dduchen_tools/miniconda3/envs/haploconduct/opt/haploconduct-0.2.1/bin/ViralQuasispecies', '--singles=../stage_b/singles.fastq', '--overlaps=../contig_overlaps.txt', '--threads=4', '--edge_threshold=0.995000', '--first_it=false', '--min_clique_size=2', '--keep_singletons=100', '--remove_branches=true', '--min_overlap_perc=0', '--min_overlap_len=100', '--merge_contigs=0.000000', '--FNO=1', '--original_readcount=145220', '--error_correction=false', '--remove_trans=1', '--optimize=false', '--verbose=false', '--diploid=false', '--base_path=/home-1/dduchen3@jhu.edu/code/dduchen_tools/miniconda3/envs/haploconduct/opt/haploconduct-0.2.1', '--min_read_len=0', '--max_tip_len=167', '--separate_tips=true', '--ignore_inclusions=true']' returned non-zero exit status -6
Traceback (most recent call last):
  File "/home-1/dduchen3@jhu.edu/code/dduchen_tools/miniconda3/envs/haploconduct/opt/haploconduct-0.2.1/savage.py", line 833, in <module>
    sys.exit(main())
  File "/home-1/dduchen3@jhu.edu/code/dduchen_tools/miniconda3/envs/haploconduct/opt/haploconduct-0.2.1/savage.py", line 433, in main
    subprocess.check_call("%s/scripts/pipeline_per_stage.py --stage b --fastq ../stage_b --overlaps %s --use_subreads --min_overlap_len %d --num_threads %d --remove_branches %s --max_tip_len %s" % (base_path, overlaps, min_overlap_len, args.threads, remove_branches, max_tip_len), shell=True)
  File "/home-1/dduchen3@jhu.edu/code/dduchen_tools/miniconda3/envs/haploconduct/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home-1/dduchen3@jhu.edu/code/dduchen_tools/miniconda3/envs/haploconduct/opt/haploconduct-0.2.1/scripts/pipeline_per_stage.py --stage b --fastq ../stage_b --overlaps ../contig_overlaps.txt --use_subreads --min_overlap_len 100 --num_threads 4 --remove_branches true --max_tip_len 167' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home-1/dduchen3@jhu.edu/code/dduchen_tools/miniconda3/envs/haploconduct/opt/haploconduct-0.2.1/haploconduct.py", line 87, in <module>
    sys.exit(main())
  File "/home-1/dduchen3@jhu.edu/code/dduchen_tools/miniconda3/envs/haploconduct/opt/haploconduct-0.2.1/haploconduct.py", line 75, in main
    subprocess.check_call(['{}/savage.py'.format(base_path)] + params)
  File "/home-1/dduchen3@jhu.edu/code/dduchen_tools/miniconda3/envs/haploconduct/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home-1/dduchen3@jhu.edu/code/dduchen_tools/miniconda3/envs/haploconduct/opt/haploconduct-0.2.1/savage.py', '-s', '../../../C4_qc/C4_pear/subsample_25k/SRR7471501_pear.assembled.150bp.fastq', '-t', '4', '--merge_contigs', '0.001', '--split', '9']' returned non-zero exit status 1
`

Any suggestions for what I might be doing incorrectly?

**Comment by AlphaSquad** [comment]
Hey, I was just about to open the same issue - I am getting the same error: 
```
SAVAGE Stage b
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
pipeline_per_stage.py
Traceback (most recent call last):
  File "/home/afritz/miniconda2/envs/haploconduct/opt/haploconduct-0.2.1/scripts/
pipeline_per_stage.py", line 666, in <module>
    sys.exit(main())
  File "/home/afritz/miniconda2/envs/haploconduct/opt/haploconduct-0.2.1/scripts/
pipeline_per_stage.py", line 164, in main
    run_first_it_merge(args.fastq, args.overlaps, args.edge_threshold, args.min_o
verlap_perc, min_overlap_len, args.merge_contigs, first_it)
  File "/home/afritz/miniconda2/envs/haploconduct/opt/haploconduct-0.2.1/scripts/
pipeline_per_stage.py", line 246, in run_first_it_merge
    "--ignore_inclusions=%s" % remove_inclusions
  File "/home/afritz/miniconda2/envs/haploconduct/lib/python2.7/subprocess.py", l
ine 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/afritz/miniconda2/envs/haplocondu
ct/opt/haploconduct-0.2.1/bin/ViralQuasispecies', '--singles=../stage_b/singles.f
astq', '--overlaps=../contig_overlaps.txt', '--threads=32', '--edge_threshold=0.995000', '--first_it=false',
 '--min_clique_size=2', '--keep_singletons=60', '--remove_branches=true', '--min_overlap_perc=0',
 '--min_overlap_len=60', '--merge_contigs=0.000000', '--FNO=1', '--original_readcount=740740',
 '--error_correction=false', '--remove_trans=1', '--optimize=false', '--verbose=false', '--diploid=false', 
'--base_path=/home/afritz/miniconda2/envs/haploconduct/opt/haploconduct-0.2.1',
 '--min_read_len=0',  '--max_tip_len=150', '--separate_tips=true', '--ignore_inclusions=true']'
 returned non-zero exit status -6 [...]
```

EDIT: Increasing the `-m` parameter (in our case to read size) lead to SAVAGE finishing regularly, but obviously there are hardly any overlaps of _read length_. This makes me think the error is connected to the data set size/number of reads (145k for you, 740k for me).

**Comment by jbaaijens** [comment]
Hi both, I'm sorry you're getting this uninformative error message. Usually std::bad_alloc means the system is out of memory, so indeed, it probably has to do with the size of the dataset. How much RAM do you have, and could you check how much SAVAGE was using? Also, were you able to run SAVAGE without issues on the example dataset?

**Comment by dduchen** [comment]
Hello,
I am able to successfully run savage de novo on the example dataset which is reassuring. I also receive this error when conducting savage-ref... and when using a single thread. 
I believe I've requested more than enough RAM for testing, here with 80GB: 
`State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 17
CPU Utilized: 12:33:02
CPU Efficiency: 9.51% of 5-11:56:37 core-walltime Job Wall-clock time: 07:45:41 Memory Utilized: 57.81 GB Memory Efficiency: 72.26% of 80.00 GB`

**Comment by jbaaijens** [comment]
Unfortunately this kind of error is really hard to diagnose. Could you try running SAVAGE on a subset of your data, say 10% of the reads, with the same parameters and see how that goes?

**Comment by dduchen** [comment]
Hello!
After re-running SAVAGE on only the longest of my assembled reads, it successfully completed. As it looks like @AlphaSquad and I had run SAVAGE initially with ~100bp Illumina reads (resulting in min overlap ~60bp), perhaps there's an issue with shorter read lengths? I had run a prior version of SAVAGE with ~100bp reads and hadn't encountered this error however... 
As I'm worried about potentially introducing some bias by only using the longest subset of reads - I'll see whether anything else might be triggering this error.

**Comment by AlphaSquad** [comment]
For me downsampling the reads with BBnorm to 1000x coverage did the trick, this hopefully did not introduce any bias and might be a possibility to do before a savage run on bigger data sets @dduchen .
