### ISSUE TITLE
Read ID does not start with @. Exiting read_pairs.

### ISSUE THREAD

**Issue by huangjj27** [HaploConduct/HaploConduct#7]
I get Some error like this:

```
**************
SAVAGE Stage a
Read ID does not start with @. Exiting read_pairs.
pipeline_per_stage.py
Traceback (most recent call last):
  File "/BIGDATA1/sysu_kyang_1/software/HaploConduct-master/scripts/pipeline_per_stage.py", line 666, in <module>
    sys.exit(main())
  File "/BIGDATA1/sysu_kyang_1/software/HaploConduct-master/scripts/pipeline_per_stage.py", line 149, in main
    run_merging_it(args.edge_threshold, args.min_overlap_perc, args.min_overlap_len, 0)
  File "/BIGDATA1/sysu_kyang_1/software/HaploConduct-master/scripts/pipeline_per_stage.py", line 356, in run_merging_it
    "--ignore_inclusions=%s" % remove_inclusions
  File "/BIGDATA1/app/python/2.7.14-gcc-4.8.5/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/BIGDATA1/sysu_kyang_1/software/HaploConduct-master/bin/ViralQuasispecies', '--singles', 'singles.fastq', '--paired1=paired1.fastq', '--paired2=paired2.fastq', '--overlaps=overlaps.txt', '--threads=24', '--edge_threshold=0.970000', '--first_it=false', '--keep_singletons=90', '--min_clique_size=2', '--remove_branches=true', '--min_overlap_perc=0', '--min_overlap_len=90', '--merge_contigs=0.000000', '--FNO=1', '--original_readcount=7500', '--error_correction=false', '--remove_trans=1', '--optimize=false', '--verbose=false', '--diploid=false', '--base_path=/BIGDATA1/sysu_kyang_1/software/HaploConduct-master', '--min_read_len=0', '--max_tip_len=150', '--separate_tips=true', '--ignore_inclusions=true']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/BIGDATA1/sysu_kyang_1/software/HaploConduct-master/savage.py", line 833, in <module>
    sys.exit(main())
  File "/BIGDATA1/sysu_kyang_1/software/HaploConduct-master/savage.py", line 385, in main
    subprocess.check_call("%s/scripts/pipeline_per_stage.py --stage a --fastq ../input_fas --overlaps %s --min_overlap_len %d --num_threads %d --remove_branches %s --max_tip_len %s --edge_threshold %s --clique_size_EC %s" %(base_path, overlaps, min_overlap_len, args.threads, remove_branches, max_tip_len, edge_threshold, args.min_clique_size), shell=True)
  File "/BIGDATA1/app/python/2.7.14-gcc-4.8.5/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/BIGDATA1/sysu_kyang_1/software/HaploConduct-master/scripts/pipeline_per_stage.py --stage a --fastq ../input_fas --overlaps ../original_overlaps.txt --min_overlap_len 90 --num_threads 24 --remove_branches true --max_tip_len 150 --edge_threshold 0.97 --clique_size_EC 4' returned non-zero exit status 1
```

and we inspect the sequence in `stage_a/patch0/input_fas/paired1.fastq` , finding out this line:
```
@98
ACACTCGAGGGCAGCAGCAATTGTTTCTCCCTACCAATAATGGTGACCACCACCGACGAGGGTGTGTTCGATTGTACTGCCGTGTGTAACGACGAACGAGCTGTGTATTTCTTTGTGCGACCCACAGACGTGTTCATAATCAACGGGTCT
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ-JJJJJJJJJJ7JJJJJJ7J7JJJ-JJJJJJJJJJJ7JJJJJJ-J7JJJ-J-JJ7JJJJJJJ7
@99
ATTTTAACGTGTCATCTAAAATCTGGTGCGGTGTTAATTCTGTTATCGTTCTTGTCTCTTCACAAATTTTGTCTACAGCACTTTGTGTTTCGTTATTATCGACTGGTAACACTATGCTCTTAACAGCGAAGGCTGTTTCACTGTTTTCGT
+
AAFFFJJJJJJJJJJJJ7JJJJJJJJJJJJJJJJJJJ7JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ-JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ7J
@100
GGGTCAGTGTGCTAATTGTATTTATAATTGGTGTAGTATTATTATTAGATGTAATATTATTAGTAATAGTAAACAAAAATGGTGACGATGCTGTGGTAGTTGAAATGTTGCTGCTAATGCTAGTAGTAGTAGCAGTATTAGTAGTACTGT
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ-JJJJJJJJJJJJJJJJJ7JJJJJJJJJJJJJJJJJJJJ-J7JJJ7JJJJJJJ
```
but in `stage_a/patch0/stage_a/paired1.fastq`, it become:
```
@98CATTGCTGTGTTGTACAATCGAGTTGTGGGTGTTGAAAATGAATTGAAAGAAACATTACAAACTA
+
~~~~~~~~~~~~~~~~~~~GGTGTCGGGCTGGACCCGTCTGATTTCCTTGAACAGAGTGATGCGAACGTTCTTGCCGGGTCCCCTGAACGGATCTTCGGTTACCATATATTGATTTATGTGTCACACTATGATAGGGTATTGTGTGCGTTACAACACACCCACCGATGACCTACACAAGAGTG
+
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@100
AAGGTTTGACAGATGACAATTGAACAAACGAAAGCCGTCTTGAATGGCGTAACAATATGTCTTGGATGATTGTTGCACACCGTAGGTGACAATGCCCACAAGTTGTTTGTGAA
```

You can find that `@99` is missing. Is that a bug?

**Comment by jbaaijens** [comment]
Hi @huangjj27, this is very strange behaviour. Indeed, it looks like a bug. Let me see if I can find it.

**Comment by jbaaijens** [comment]
@huangjj27 could you send me (a subset of) your data such that allows me to reproduce this issue?
