### ISSUE TITLE
SAVAGE: unverbal error message

### ISSUE THREAD

**Issue by stefanches7** [HaploConduct/HaploConduct#8]
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 149) >= this->size() (which is 149)
Traceback (most recent call last):
  File "/data/nasif12/home_if12/dvoretsk/projects/V-pipe-SARS/.snakemake/conda/7f128bd5/opt/savage-0.4.2/scripts/pipeline_per_stage.py", line 666, in <module>
    sys.exit(main())
  File "/data/nasif12/home_if12/dvoretsk/projects/V-pipe-SARS/.snakemake/conda/7f128bd5/opt/savage-0.4.2/scripts/pipeline_per_stage.py", line 141, in main
    run_error_correction(args.fastq, args.overlaps, args.edge_threshold, args.min_overlap_perc, min_overlap_len_EC, args.merge_contigs, first_it, args.clique_size_EC)
  File "/data/nasif12/home_if12/dvoretsk/projects/V-pipe-SARS/.snakemake/conda/7f128bd5/opt/savage-0.4.2/scripts/pipeline_per_stage.py", line 406, in run_error_correction
    "--ignore_inclusions=%s" % remove_inclusions
  File "/data/nasif12/home_if12/dvoretsk/projects/V-pipe-SARS/.snakemake/conda/7f128bd5/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/data/nasif12/home_if12/dvoretsk/projects/V-pipe-SARS/.snakemake/conda/7f128bd5/opt/savage-0.4.2/bin/ViralQuasispecies', '--singles', '../input_fas/singles.fastq', '--paired1', '../input_fas/paired1.fastq', '--paired2', '../input_fas/paired2.fastq', '--overlaps=../original_overlaps.txt', '--threads=4', '--edge_threshold=0.970000', '--first_it=true', '--cliques=true', '--error_correction=true', '--keep_singletons=1000', '--min_clique_size=4', '--remove_branches=false', '--min_overlap_perc=0', '--min_overlap_len=84', '--merge_contigs=0.000000', '--FNO=3', '--original_readcount=2431', '--remove_trans=2', '--optimize=false', '--verbose=false', '--base_path=/data/nasif12/home_if12/dvoretsk/projects/V-pipe-SARS/.snakemake/conda/7f128bd5/opt/savage-0.4.2', '--min_read_len=0', '--max_tip_len=140', '--separate_tips=false', '--ignore_inclusions=false']' returned non-zero exit status -6
Traceback (most recent call last):
  File "/data/nasif12/home_if12/dvoretsk/projects/V-pipe-SARS/.snakemake/conda/7f128bd5/opt/savage-0.4.2/savage.py", line 833, in <module>
    sys.exit(main())
  File "/data/nasif12/home_if12/dvoretsk/projects/V-pipe-SARS/.snakemake/conda/7f128bd5/opt/savage-0.4.2/savage.py", line 385, in main
    subprocess.check_call("%s/scripts/pipeline_per_stage.py --stage a --fastq ../input_fas --overlaps %s --min_overlap_len %d --num_threads %d --remove_branches %s --max_tip_len %s --edge_threshold %s --clique_size_EC %s" %(base_path, overlaps, min_overlap_len, args.threads, remove_branches, max_tip_len, edge_threshold, args.min_clique_size), shell=True)
  File "/data/nasif12/home_if12/dvoretsk/projects/V-pipe-SARS/.snakemake/conda/7f128bd5/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/data/nasif12/home_if12/dvoretsk/projects/V-pipe-SARS/.snakemake/conda/7f128bd5/opt/savage-0.4.2/scripts/pipeline_per_stage.py --stage a --fastq ../input_fas --overlaps ../original_overlaps.txt --min_overlap_len 84 --num_threads 4 --remove_branches true --max_tip_len 140 --edge_threshold 0.97 --clique_size_EC 4' returned non-zero exit status 1
```

**Comment by jbaaijens** [comment]
Hi @stefanches7,

At first glance this might be a fastq formatting issue, but it's hard to diagnose without further information. At what stage did this error occur? Could you add the entire savage log?

Thanks,
Jasmijn
