### ISSUE TITLE
savage preprocessing error

### ISSUE THREAD

**Issue by keirballa** [HaploConduct/HaploConduct#9]
Hello Jasmijn, I am trying to run savage-ref mode using single and paired-end reads processed with PEAR, but get an error after running for an hour that seems to have something to do with the random_split_fastq.py script, or possibly I am invoking --split incorrectly:

```
ERROR: can't find matching identifier for read pair
@A00223:107:H73Y5DRXX:1:1144:11731:25128
@A00223:107:H73Y5DRXX:1:1144:11731:25128

-------------------------------------------
SAVAGE - Strain Aware VirAl GEnome assembly
-------------------------------------------
Version: 0.4.2
Author: Jasmijn Baaijens
    
Command used:
/uufs/chpc.utah.edu/common/home/u6010867/.conda/envs/SAVAGE/opt/savage-0.4.2/savage.py --ref /scratch/kingspeak/serial/u6010867/langlois/virus-vg_langlois/alphacoronavirus_consensus1.fa --split 2 --merge_contigs 0.01 -s pear_langlois.assembled.fastq -p1 pear_langlois.unassembled.forward.fastq -p2 pear_langlois.unassembled.reverse.fastq -t 16

Parameter values:
filtering = True
reference = /scratch/kingspeak/serial/u6010867/langlois/virus-vg_langlois/alphacoronavirus_consensus1.fa
merge_contigs = 0.01
remove_branches = True
contig_len_stage_c = 100
split_num = 2
use_subreads = True
no_assembly = False
diploid_contig_len = 200
overlap_stage_c = 100
input_p2 = pear_langlois.unassembled.reverse.fastq
input_p1 = pear_langlois.unassembled.forward.fastq
count_strains = False
min_clique_size = 4
diploid_overlap_len = 30
compute_overlaps = True
preprocessing = True
threads = 16
stage_a = True
stage_b = True
stage_c = True
max_tip_len = None
min_overlap_len = None
outdir = .
average_read_len = None
sfo_mm = 50
revcomp = False
input_s = pear_langlois.assembled.fastq
diploid = False

Input fastq stats:
Number of single-end reads = 3447342
Number of paired-end reads = 430739896
Total number of bases = 22232309216
Average sequence length = 51.2

Using max_tip_len = 51
Using min_overlap_len = 31

----------------------------------------------------------------
WARNING: min_overlap_len = 31
For more accurate error correction, increase the minimal overlap length using --min_overlap_len
----------------------------------------------------------------
*******************
Preprocessing input
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u6010867/.conda/envs/SAVAGE/opt/savage-0.4.2/savage.py", line 833, in <module>
    sys.exit(main())
  File "/uufs/chpc.utah.edu/common/home/u6010867/.conda/envs/SAVAGE/opt/savage-0.4.2/savage.py", line 294, in main
    subprocess.check_call("%s/scripts/random_split_fastq.py --input %s --input2 %s --output %s/stage_a/paired --split_num %s" % (base_path, args.input_p1, args.input_p2, args.outdir, args.split_num), shell=True)
  File "/uufs/chpc.utah.edu/common/home/u6010867/.conda/envs/SAVAGE/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/uufs/chpc.utah.edu/common/home/u6010867/.conda/envs/SAVAGE/opt/savage-0.4.2/scripts/random_split_fastq.py --input pear_langlois.unassembled.forward.fastq --input2 pear_langlois.unassembled.reverse.fastq --output ./stage_a/paired --split_num 2' returned non-zero exit status 1
```

Thank you for your help,
-Keir

**Comment by jbaaijens** [comment]
Hi Keir,

Hmm that is strange, I've never seen this error but it might have to do with reference-guided mode. Let me see if I can find the issue, I'll get back to you about this.

Btw, I notice that you're processing a massive number of reads and I honestly can't say if this will be feasible; I've never tried anything like this. In any case, I would recommend starting with a small subsample and if that runs smoothly try to scale up.
